# Generated by Django 5.2.14 on 2026-05-08 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(blank=True, max_length=60)),
                ('context_id', models.CharField(blank=True, max_length=36)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=12)),
                ('content', models.TextField()),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='common.aichatsession')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('style_recommendation', 'Style Recommendation'), ('measurement_assist', 'Measurement Assist'), ('design_suggestion', 'Design Suggestion'), ('fabric_suggestion', 'Fabric Suggestion'), ('price_estimation', 'Price Estimation'), ('chatbot', 'Chatbot')], db_index=True, max_length=40)),
                ('model_name', models.CharField(max_length=100)),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_interaction_logs',
            },
        ),
        migrations.CreateModel(
            name='AIMeasurementSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flagged_fields', models.JSONField(default=list)),
                ('correction_notes', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_measurement_suggestions', to=settings.AUTH_USER_MODEL)),
                ('input_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.measurement')),
                ('interaction_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_suggestion', to='common.aiinteractionlog')),
            ],
            options={
                'db_table': 'ai_measurement_suggestions',
            },
        ),
        migrations.CreateModel(
            name='AIPriceEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basis_notes', models.TextField(blank=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_estimate', to='common.aiinteractionlog')),
                ('stitch_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_price_estimates', to='orders.stitchrequest')),
            ],
            options={
                'db_table': 'ai_price_estimates',
            },
        ),
        migrations.CreateModel(
            name='AIStyleRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('fabric_prefs', models.JSONField(default=list)),
                ('suggestions', models.JSONField()),
                ('was_acted_on', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_style_recommendations', to=settings.AUTH_USER_MODEL)),
                ('interaction_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_recommendation', to='common.aiinteractionlog')),
            ],
            options={
                'db_table': 'ai_style_recommendations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('stitch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.stitchrequest')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiinteractionlog',
            index=models.Index(fields=['feature_type', 'created_at'], name='ai_interact_feature_3fe3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteractionlog',
            index=models.Index(fields=['user', 'created_at'], name='ai_interact_user_id_610177_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['stitch_request', 'sent_at'], name='messages_stitch__293743_idx'),
        ),
    ]
