# Generated by Django 5.2.14 on 2026-05-08 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('garment_type', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('pattern', models.CharField(blank=True, max_length=80)),
                ('design_details', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('stitching', 'Stitching'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stitch_requests', to=settings.AUTH_USER_MODEL)),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.measurement')),
                ('reference_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designs.design')),
                ('tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stitch_requests',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('stitching', 'Stitching'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('stitching', 'Stitching'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stitch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.stitchrequest')),
            ],
            options={
                'db_table': 'order_status_logs',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='StitchRequestImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='stitch_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stitch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.stitchrequest')),
            ],
            options={
                'db_table': 'stitch_request_images',
            },
        ),
        migrations.CreateModel(
            name='DesignOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='payment_pending', max_length=20)),
                ('order_date', models.DateField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='designs.design')),
            ],
            options={
                'db_table': 'design_orders',
                'indexes': [models.Index(fields=['customer', 'status'], name='design_orde_custome_dfbc04_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stitchrequest',
            index=models.Index(fields=['customer', 'status'], name='stitch_requ_custome_224c87_idx'),
        ),
        migrations.AddIndex(
            model_name='stitchrequest',
            index=models.Index(fields=['tailor', 'status'], name='stitch_requ_tailor__d684c1_idx'),
        ),
    ]
