# Generated by Django 5.2.14 on 2026-05-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stitchrequest',
            name='design_details',
            field=models.TextField(blank=True, default=dict),
        ),
    ]
