# Generated by Django 5.2.14 on 2026-05-27 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_stitchrequest_design_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('required_measurements', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Garment Categories',
                'db_table': 'garment_categories',
            },
        ),
        migrations.AlterField(
            model_name='stitchrequest',
            name='design_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stitchrequest',
            name='garment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitch_requests', to='orders.garmentcategory'),
        ),
    ]
