# Generated by Django 5.2.14 on 2026-05-08 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'design_tags',
            },
        ),
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='designs.designcategory')),
            ],
            options={
                'verbose_name_plural': 'Design categories',
                'db_table': 'design_categories',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designs.designcategory')),
            ],
            options={
                'db_table': 'designs',
            },
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='designs/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designs.design')),
            ],
            options={
                'db_table': 'design_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DesignTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_maps', to='designs.design')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.designtag')),
            ],
            options={
                'db_table': 'design_tag_map',
            },
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['tailor', 'is_active'], name='designs_tailor__59149e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designtagmap',
            unique_together={('design', 'tag')},
        ),
    ]
