# Generated by Django 5.2.14 on 2026-05-08 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('specialisation', models.CharField(max_length=100)),
                ('qualification', models.CharField(choices=[('diploma', 'Diploma in Fashion'), ('bsc_fashion_design', 'B.Sc Fashion Design'), ('ba_costume_design', 'B.A Costume Design'), ('pg_fashion_design', 'P.G Fashion Design'), ('5_years_experience', '5 Years Experience'), ('10_years_experience', '10 Years Experience'), ('other', 'Other')], max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/tailors/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tailor_profiles',
                'indexes': [models.Index(fields=['approval_status'], name='tailor_prof_approva_13a92b_idx')],
            },
        ),
    ]
